-- WhatsApp templates : 8 familles metier x 3 statuts x 4 messages = 96 INSERTs
-- Sequences : BTP, MECA, BEAUTE_F, BEAUTE_M, CREATIF, TRANSPORT, RESTAURATION, DIGITAL

INSERT INTO wolo_whatsapp_templates (key, sequence, step, delay_hours, content) VALUES
-- ========== BTP ==========
-- M_apprenti_btp (Kodjo, apprenti macon, Akpakpa Cotonou)
('M_apprenti_btp_1', 'M_apprenti_btp', 1, 0, 'Salut {prenom}. Tu es apprenti sur les chantiers a {ville} ? Tu connais le truc : samedi tu bosses gratuit pour le patron, lundi il oublie ton transport. Tu apprends le metier, oui. Mais ton nom, personne le connait. Sur WOLO Market tu existes deja. Photo, quartier, specialite (carrelage, briques, fer a beton). Le prochain chantier que tu vas trouver, c''est le tien. Pas celui du patron. Crée ton profil maintenant : {url_dashboard}'),
('M_apprenti_btp_2', 'M_apprenti_btp', 2, 72, 'Kodjo, apprenti macon a Akpakpa, a fait une chose simple : il a poste 4 photos de mur qu''il a monte tout seul, meme sans le patron. Trois semaines apres, un proprietaire l''a appele direct pour une cloture. 35 000 FCFA pour lui seul. Toi {prenom}, fais pareil. Photo nette du mur ou du carrelage que TU as pose. Nomme le quartier. Ecris en 2 lignes ce que tu sais faire. Pas besoin d''etre patron pour avoir un client. Mets a jour ton profil : {url_dashboard}'),
('M_apprenti_btp_3', 'M_apprenti_btp', 3, 336, '{prenom}, ecoute bien. WOLO Market te paie 40% sur chaque parrain Pro que tu ramenes. Ton patron, ton tonton macon, le menuisier d''a cote, le plombier du quartier. Chaque pro qui paie 2 500 FCFA Pro grace a toi = 1 000 FCFA dans ta poche. Chaque mois. Recurrent. 10 parrains = 10 000 FCFA/mois sans bosser. C''est ton argent de poche apprenti. Lien de parrainage : {url_parrainage}'),
('M_apprenti_btp_4', 'M_apprenti_btp', 4, 720, '{prenom}, 30 jours sur WOLO. Tu as vu comment ca marche. Maintenant la vraie question : tu restes apprenti invisible ou tu deviens un nom dans ton quartier ? Le Plan Pro 2 500 FCFA/mois, c''est pas un abonnement, c''est ton outil d''independance. Tu apparais en premier dans les recherches, tu publies tes propres mini-offres, tu acces King & Queen apres 2 mois (500K FCFA distribues/mois). 2 500 FCFA = 2 sachets de riz. Ton independance vaut plus. Active : {url_dashboard}'),

-- M_indep_btp (artisan independant BTP)
('M_indep_btp_1', 'M_indep_btp', 1, 0, '{prenom}, tu es macon/electricien/plombier independant a {ville}. Le probleme tu le connais : tu finis un chantier, et apres ? Tu attends que le bouche-a-oreille tourne. Parfois 2 semaines sans appel. Ton telephone reste froid. Sur WOLO Market, ton profil bosse pendant que tu dors. Les clients du quartier te trouvent par metier, par localisation. Photo de tes chantiers, devis clair, contact direct. Active ton profil : {url_dashboard}'),
('M_indep_btp_2', 'M_indep_btp', 2, 72, 'Kossi, electricien independant a {ville}, a fait ca : 6 photos de tableaux electriques propres, prix moyen affiche (15 000 FCFA installation simple), zone de deplacement. En 10 jours il a recu 4 demandes. Toi {prenom} : poste tes 3 derniers chantiers, ecris ton tarif moyen, indique tes quartiers. Les clients qui cherchent un pro fiable veulent VOIR ce que tu fais. Pas un CV. Des preuves. Mets ton profil a jour : {url_dashboard}'),
('M_indep_btp_3', 'M_indep_btp', 3, 336, '{prenom}, opportunite revenus secondaires. WOLO Market te reverse 40% sur tout pro que tu parraines en Plan Pro. Tu connais combien d''artisans ? 5 ? 10 ? 20 ? Chaque parrain Pro = 1 000 FCFA dans ta poche chaque mois. Recurrent. C''est pas du one-shot. Tant qu''il reste Pro, tu touches. 15 parrains = 15 000 FCFA/mois passif. Lien dedie : {url_parrainage}'),
('M_indep_btp_4', 'M_indep_btp', 4, 720, '{prenom}, 30 jours. Soit ton profil dort, soit il bosse pour toi. Le Plan Pro a 2 500 FCFA/mois, c''est ton outil d''independance economique : remontee dans les recherches, badge Pro verifie (le client te fait confiance direct), King & Queen apres 2 mois (500K FCFA distribues/mois entre H et F), publication d''offres si tu cherches un apprenti. 2 500 FCFA = un demi-sac de ciment. Ton chiffre d''affaires merite mieux. Active : {url_dashboard}'),

-- M_patron_btp (patron entreprise BTP)
('M_patron_btp_1', 'M_patron_btp', 1, 0, '{prenom}, tu diriges une entreprise BTP a {ville}. Tu jongles entre 3 chantiers, 8 ouvriers, et un client qui change d''avis tous les jours. Ton vrai probleme : recruter un macon fiable. Tu paies des annonces sur Facebook, tu recois 80 messages, 75 sont des arnaques. Sur WOLO Market, tu publies une offre, les candidats ont DEJA un profil verifie, photos de chantiers, scoring fiabilite. Tu choisis sans perdre 4 jours. Active ton compte recruteur : {url_dashboard}'),
('M_patron_btp_2', 'M_patron_btp', 2, 72, 'Mawuli, patron BTP a {ville}, a recrute 2 macons en 5 jours via WOLO. Comment ? Offre claire (chantier 3 mois, 80 000 FCFA/mois), photos du chantier en cours, questions knockout (tu as deja monte un mur de 2m ? oui/non). 12 candidats, 4 retenus, 2 embauches. Pas de Facebook chaos. Toi {prenom} : publie ton offre maintenant, ajoute 2 photos chantier, sois precis sur le metier. Le candidat serieux repond en 24h. {url_dashboard}'),
('M_patron_btp_3', 'M_patron_btp', 3, 336, '{prenom}, tu connais combien d''autres patrons BTP a {ville} ? Ton fournisseur de ciment, le carreleur d''a cote, l''entreprise du cousin. Chaque patron que tu parraines en Plan Pro = 1 000 FCFA/mois pour toi. Recurrent. Tu n''as rien a vendre, juste partager ton lien. 10 patrons parraines = 10 000 FCFA passif chaque mois. Et eux gagnent un outil de recrutement. Win-win. Lien parrainage : {url_parrainage}'),
('M_patron_btp_4', 'M_patron_btp', 4, 720, '{prenom}, 30 jours sur WOLO. Tu as vu : recrutement plus rapide, candidats verifies, moins de stress. Le Plan Pro 2 500 FCFA/mois, c''est l''outil d''independance de ton entreprise : offres illimitees, pipeline candidats (kanban), filtres avances (experience, quartier, age), King & Queen entreprise apres 2 mois. 2 500 FCFA = 2 sacs de gravier. Ton entreprise vaut plus que ca. Active : {url_dashboard}'),

-- ========== MECA ==========
-- M_apprenti_meca (Yawo, apprenti mecano, Avedji Lome)
('M_apprenti_meca_1', 'M_apprenti_meca', 1, 0, '{prenom}, apprenti mecano a {ville}. Le scenario : tu repares la voiture, le patron encaisse, toi tu prends le pourboire si le client est sympa. Tu connais les moteurs mieux que lui. Mais ton nom ? Personne le sait. Sur WOLO Market, tu as un profil pro : photos de moteurs que tu as repares, specialites (vidange, distribution, embrayage). Les voisins du quartier qui ont besoin d''une petite reparation viennent direct chez toi. Cree ton profil : {url_dashboard}'),
('M_apprenti_meca_2', 'M_apprenti_meca', 2, 72, 'Yawo, apprenti mecano a Avedji, a poste 3 photos : un moteur ouvert qu''il a remonte, une vidange propre, un embrayage change. Resultat : 2 voisins l''ont appele pour une vidange a domicile (5 000 FCFA chacun) le week-end. 10 000 FCFA en plus de son apprentissage. Toi {prenom} : poste 3 photos de tes interventions, indique ce que tu sais faire seul. Le client de quartier paie cash, sans intermediaire. Mets ton profil a jour : {url_dashboard}'),
('M_apprenti_meca_3', 'M_apprenti_meca', 3, 336, '{prenom}, parrainage WOLO = 40% recurrent. Tu connais combien de mecanos, electroniciens auto, vendeurs de pieces detachees ? 10 ? 15 ? Chaque pro que tu inscris en Plan Pro grace a ton lien = 1 000 FCFA/mois pour toi. Tant qu''il reste Pro, tu touches. 12 parrains = 12 000 FCFA/mois. C''est ton salaire d''apprenti X3. Lien dedie : {url_parrainage}'),
('M_apprenti_meca_4', 'M_apprenti_meca', 4, 720, '{prenom}, 30 jours. Tu as compris : ton metier vaut plus que ce que ton patron te donne. Le Plan Pro 2 500 FCFA/mois, c''est pas un luxe, c''est ton independance. Tu apparais en premier quand un client cherche un mecano dans ton quartier, tu acces King & Queen apres 2 mois (500K FCFA distribues/mois H+F), badge Pro qui rassure. 2 500 FCFA = 2 vidanges que tu factures direct. Active : {url_dashboard}'),

-- M_indep_meca (mecano independant)
('M_indep_meca_1', 'M_indep_meca', 1, 0, '{prenom}, mecano independant a {ville}. Tu as ton garage, tes outils, ton experience. Mais ton chiffre d''affaires depend des memes 20 clients fideles. Quand l''un part, tu sens le trou. Sur WOLO Market, les clients neufs te trouvent par metier (mecano auto, electronicien, climatisation), par quartier, par specialite. Photo de ton garage, tarifs moyens, contact direct. Profil actif = telephone qui sonne. Active : {url_dashboard}'),
('M_indep_meca_2', 'M_indep_meca', 2, 72, 'Adjo, mecano independant a {ville}, a publie : photo garage, 5 specialites (vidange 3 000, distribution 25 000, embrayage 35 000, climatisation 15 000, diagnostic 5 000). 7 nouveaux clients en 2 semaines. Toi {prenom} : tarifs clairs = clients qui appellent direct sans negocier 30 minutes. Mets a jour ton profil avec tes prix : {url_dashboard}'),
('M_indep_meca_3', 'M_indep_meca', 3, 336, '{prenom}, opportunite cash en plus. Parrainage WOLO Pro = 40% recurrent par mois. Tu connais des collegues mecanos, des vendeurs de pieces, des laveurs auto, des chauffeurs proprios ? Chaque parrain Pro = 1 000 FCFA dans ta poche chaque mois tant qu''il reste actif. 20 parrains = 20 000 FCFA/mois passif. Pendant que tu repares un moteur, ton lien bosse. Active ton lien : {url_parrainage}'),
('M_indep_meca_4', 'M_indep_meca', 4, 720, '{prenom}, 30 jours. Le Plan Pro 2 500 FCFA/mois = ton independance economique. Remontee dans les recherches, badge verifie (le client mefiant te fait confiance), King & Queen apres 2 mois (500K distribues/mois), publication d''offres si tu cherches un apprenti serieux. 2 500 FCFA = une demi-vidange. Ton garage vaut plus. Active : {url_dashboard}'),

-- M_patron_meca (patron garage)
('M_patron_meca_1', 'M_patron_meca', 1, 0, '{prenom}, tu diriges un garage a {ville}. 4-8 mecanos, des outils, une reputation. Ton probleme du moment : ton meilleur mecano est parti chez la concurrence. Tu cherches un remplacant fiable. WhatsApp diffuse 100 fois, 90% des candidats ne savent rien faire. Sur WOLO Market, profils verifies, photos de leurs interventions, scoring fiabilite. Tu publies, tu filtres, tu choisis. Active ton compte recruteur : {url_dashboard}'),
('M_patron_meca_2', 'M_patron_meca', 2, 72, 'Komi, patron garage a {ville}, a recrute 1 mecano en 6 jours via WOLO. Offre claire (mecano experimente distribution+embrayage, 90 000 FCFA/mois), photo de l''atelier, question knockout (tu as deja change une distribution sur diesel ? oui/non). 9 candidats, 3 retenus, 1 embauche. Pas de WhatsApp pourri. Toi {prenom} : publie ton offre, sois precis, gain de temps assure. {url_dashboard}'),
('M_patron_meca_3', 'M_patron_meca', 3, 336, '{prenom}, tu connais d''autres patrons garage a {ville} ? Le carrossier d''a cote, le specialiste clim, le vendeur de pieces detachees ? Parrainage WOLO Pro = 40% recurrent. Chaque patron que tu inscris = 1 000 FCFA/mois pour toi. 8 parrains = 8 000 FCFA/mois passif. Lien dedie : {url_parrainage}'),
('M_patron_meca_4', 'M_patron_meca', 4, 720, '{prenom}, 30 jours. Le Plan Pro 2 500 FCFA/mois = outil d''independance entreprise. Offres illimitees, pipeline candidats kanban, filtres (experience moteur essence/diesel, quartier, age), King & Queen apres 2 mois (500K distribues). 2 500 FCFA = un kit de bougies. Ton garage merite mieux. Active : {url_dashboard}'),

-- ========== BEAUTE_F ==========
-- M_apprentie_beaute (Esther, apprentie esthe, Be Lome)
('M_apprentie_beaute_1', 'M_apprentie_beaute', 1, 0, '{prenom}, apprentie esthe/maquilleuse/onglerie a {ville}. Tu connais le truc : tu fais 3 manucures par jour au salon, la patronne encaisse 15 000, toi tu touches 1 500 si elle se souvient. Tu apprends, oui. Mais tes mains valent deja de l''argent. Sur WOLO Market, tu existes comme pro. Photos de tes ongles, maquillages, soins. Specialite (gel, nail art, maquillage soiree). Les clientes du quartier viennent te chercher TOI. Cree ton profil : {url_dashboard}'),
('M_apprentie_beaute_2', 'M_apprentie_beaute', 2, 72, 'Esther, apprentie esthe a Be, a poste 6 photos : nail art, manucure simple, maquillage mariage. En 2 semaines, 5 clientes l''ont appelee a domicile pour le week-end. 3 000 FCFA la prestation. 15 000 FCFA en plus de son apprentissage. Toi {prenom} : 6 photos de TES realisations, specialite claire, quartiers couverts. Les femmes veulent VOIR avant de payer. Mets a jour : {url_dashboard}'),
('M_apprentie_beaute_3', 'M_apprentie_beaute', 3, 336, '{prenom}, parrainage WOLO = 40% recurrent. Tu connais combien de coiffeuses, esthe, couturieres, maquilleuses, bonnes vendeuses ? 15 ? 30 ? Chaque pro que tu inscris en Plan Pro grace a ton lien = 1 000 FCFA/mois pour toi. Tant qu''elle reste Pro, tu touches. 20 parrains = 20 000 FCFA/mois. C''est ton independance economique. Lien : {url_parrainage}'),
('M_apprentie_beaute_4', 'M_apprentie_beaute', 4, 720, '{prenom}, 30 jours. Tu as compris : ta patronne ne te donnera jamais ce que tu vaux. Le Plan Pro 2 500 FCFA/mois = ton independance. Premier dans les recherches "esthe {ville}", badge Pro verifie, acces Queen WOLO apres 2 mois (500K FCFA distribues/mois entre H et F). 2 500 FCFA = 2 manucures. Ton talent vaut plus. Active : {url_dashboard}'),

-- M_indep_beaute (esthe independante)
('M_indep_beaute_1', 'M_indep_beaute', 1, 0, '{prenom}, esthe/maquilleuse/onglerie independante a {ville}. Ton agenda depend de tes 30 fideles et d''Instagram. Quand l''algorithme baisse ta visibilite, ton CA chute. Sur WOLO Market, tu n''as pas a payer Meta. Profil pro, photos avant/apres, specialites, deplacement domicile. Les clientes te trouvent par recherche locale, sans algorithme qui change tous les 3 mois. Active : {url_dashboard}'),
('M_indep_beaute_2', 'M_indep_beaute', 2, 72, 'Adjoavi, esthe independante a {ville}, a poste 8 photos avant/apres (regard amande, lash lift, nail art mariage), 5 prestations avec prix (manucure 5 000, lash 15 000, maquillage mariage 25 000). 11 nouvelles clientes en 3 semaines. Toi {prenom} : photos avant/apres = preuve. Prix clairs = pas de nego. Mets a jour : {url_dashboard}'),
('M_indep_beaute_3', 'M_indep_beaute', 3, 336, '{prenom}, parrainage 40% recurrent. Tu connais combien de pros femmes ? Coiffeuses, couturieres, esthe, mannequins, bonnes vendeuses, traiteur. 15 ? 25 ? Chaque inscription Pro grace a ton lien = 1 000 FCFA/mois recurrent. 20 parrainages = 20 000 FCFA/mois passif. Pendant tu poses tes ongles, ton lien bosse. {url_parrainage}'),
('M_indep_beaute_4', 'M_indep_beaute', 4, 720, '{prenom}, 30 jours. Le Plan Pro 2 500 FCFA/mois = ton independance. Premier dans les recherches "esthe/onglerie {ville}", badge Pro, Queen WOLO apres 2 mois (500K distribues/mois H+F, ce moi-ci tu peux gagner), publication d''offres si tu cherches une apprentie. 2 500 FCFA = une seance lash. Ton salon merite. Active : {url_dashboard}'),

-- M_patronne_beaute (patronne salon)
('M_patronne_beaute_1', 'M_patronne_beaute', 1, 0, '{prenom}, tu diriges un institut/salon esthe/onglerie a {ville}. 3-6 employees, des produits, une clientele. Probleme : tu cherches une bonne maquilleuse, une esthe formee. Tu publies sur Facebook, 50 candidates, 45 disent "j''apprends vite", 0 expe reelle. Sur WOLO Market, profils verifies, photos de realisations, scoring fiabilite, badges. Tu choisis sur preuves visuelles. Active recruteur : {url_dashboard}'),
('M_patronne_beaute_2', 'M_patronne_beaute', 2, 72, 'Mireille, patronne institut a {ville}, a recrute 1 esthe en 4 jours via WOLO. Offre : esthe experimentee soin visage + lash, 70 000 FCFA/mois. Photos institut, question knockout (tu as deja fait un lash lift seule ? oui/non). 8 candidates, 2 retenues, 1 embauchee. Pas d''Instagram chaos. Toi {prenom} : offre claire + photos = candidates serieuses uniquement. {url_dashboard}'),
('M_patronne_beaute_3', 'M_patronne_beaute', 3, 336, '{prenom}, tu connais d''autres patronnes salon, instituts, boutiques mode ? Parrainage WOLO Pro = 40% recurrent. Chaque patronne inscrite Pro grace a toi = 1 000 FCFA/mois. 10 parrainages = 10 000 FCFA/mois passif. Tu fais grandir le reseau de pros femmes ouest-africaines + tu touches. {url_parrainage}'),
('M_patronne_beaute_4', 'M_patronne_beaute', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = independance entreprise. Offres illimitees, pipeline candidates kanban, filtres (experience lash/maquillage/onglerie, quartier), Queen WOLO entreprise apres 2 mois. 2 500 FCFA = un produit cosmetique. Ton institut vaut plus. Active : {url_dashboard}'),

-- ========== BEAUTE_M ==========
-- M_apprenti_barber (Mawuli, apprenti barbier, Adidogome Lome)
('M_apprenti_barber_1', 'M_apprenti_barber', 1, 0, '{prenom}, apprenti barbier/tatoueur a {ville}. Le truc tu le sais : 8 coupes par jour au salon, le patron encaisse 1 000 par tete = 8 000, toi tu touches 800 si t''es chanceux. Tes mains valent plus. Sur WOLO Market, tu te montres comme pro. Photos de tes coupes (degrade, fade, design), tatouages que tu as fait. Les jeunes du quartier viennent direct chez toi le week-end. Profil : {url_dashboard}'),
('M_apprenti_barber_2', 'M_apprenti_barber', 2, 72, 'Mawuli, apprenti barbier a Adidogome, a poste 5 photos : 2 fade, 1 dessin geometrique, 1 barbe taillee. En 10 jours, 8 jeunes l''ont appele pour coupe a domicile le samedi. 1 500 FCFA la coupe = 12 000 FCFA. Toi {prenom} : photos nettes de TES coupes, specialite claire (fade, design, barbe), quartiers. Les jeunes paient pour le style, pas pour le salon. Mets a jour : {url_dashboard}'),
('M_apprenti_barber_3', 'M_apprenti_barber', 3, 336, '{prenom}, parrainage 40% recurrent. Tu connais combien de barbiers, tatoueurs, coiffeurs hommes, dread artists ? 10 ? 20 ? Chaque pro que tu inscris en Pro = 1 000 FCFA/mois pour toi. Recurrent tant qu''il reste actif. 15 parrains = 15 000 FCFA/mois. C''est ton chiffre apprenti X4. Lien : {url_parrainage}'),
('M_apprenti_barber_4', 'M_apprenti_barber', 4, 720, '{prenom}, 30 jours. Le Plan Pro 2 500 FCFA/mois, c''est pas pour le patron, c''est pour toi. Premier dans les recherches "barbier {ville}", badge Pro, King WOLO apres 2 mois (500K distribues/mois H+F). 2 500 FCFA = 2 coupes que tu factures direct. Active : {url_dashboard}'),

-- M_indep_barber (barbier independant)
('M_indep_barber_1', 'M_indep_barber', 1, 0, '{prenom}, barbier/tatoueur independant a {ville}. Ton fauteuil tourne grace au bouche-a-oreille et a Instagram. Quand un client demenage, tu sens. Sur WOLO Market, profil pro, photos avant/apres, specialites (fade, design, dreadlocks, tatouage), zone deplacement. Les jeunes du quartier te trouvent par recherche directe. Active : {url_dashboard}'),
('M_indep_barber_2', 'M_indep_barber', 2, 72, 'Kossi, barbier indep a {ville}, a poste 10 photos coupes signature, prix clairs (coupe simple 2 000, fade design 3 500, barbe 1 500). 9 nouveaux clients en 2 semaines. Toi {prenom} : photos = preuve, prix = serenite client. Mets a jour : {url_dashboard}'),
('M_indep_barber_3', 'M_indep_barber', 3, 336, '{prenom}, parrainage 40% recurrent. Combien de barbiers, tatoueurs, coiffeurs dans tes contacts ? Chaque inscription Pro grace a ton lien = 1 000 FCFA/mois recurrent. 18 parrains = 18 000 FCFA/mois passif. {url_parrainage}'),
('M_indep_barber_4', 'M_indep_barber', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = independance. Premier dans recherches "barbier {ville}", King WOLO apres 2 mois (500K distribues/mois), publication offres apprenti. 2 500 FCFA = une fade. Active : {url_dashboard}'),

-- M_patron_barber (patron salon barbier)
('M_patron_barber_1', 'M_patron_barber', 1, 0, '{prenom}, tu diriges un salon barber/tatoo a {ville}. 3-5 barbiers, ambiance jeune, reputation locale. Probleme : tu cherches un barbier qui maitrise le fade et le design, pas un debutant qui crame des tetes. Sur WOLO Market, profils verifies avec photos de coupes reelles, scoring. Active recruteur : {url_dashboard}'),
('M_patron_barber_2', 'M_patron_barber', 2, 72, 'Yao, patron barber a {ville}, a recrute 1 barbier en 5 jours via WOLO. Offre : barbier fade+design, 50 000 FCFA/mois + 30% sur prestations. Question knockout (tu as deja fait un design geometrique seul ? photo svp). 7 candidats, 3 retenus, 1 embauche. Toi {prenom} : exige photos = filtre auto. {url_dashboard}'),
('M_patron_barber_3', 'M_patron_barber', 3, 336, '{prenom}, parrainage 40% recurrent. Tu connais d''autres patrons salon, tatoueurs, coiffeurs ? 1 000 FCFA/mois par parrain Pro recurrent. 12 parrains = 12 000 FCFA/mois. {url_parrainage}'),
('M_patron_barber_4', 'M_patron_barber', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = outil entreprise. Offres illimitees, pipeline kanban, filtres specialites, King WOLO entreprise apres 2 mois. 2 500 FCFA = 2 packs de lames. Ton salon merite. Active : {url_dashboard}'),

-- ========== CREATIF ==========
-- M_freelance_debutant_creatif (Akossiwa, photographe debutante, Akpakpa)
('M_freelance_debutant_creatif_1', 'M_freelance_debutant_creatif', 1, 0, '{prenom}, tu te lances en photo/video/graphisme a {ville}. Le piege tu le vois deja : un cousin demande "free pour la visibilite", un ami demande "remise speciale", et toi tu travailles 3 jours pour 5 000 FCFA. Sur WOLO Market, tu existes comme pro. Tarifs affiches, portfolio en ligne, contact direct. Le client vient avec son budget, pas avec son histoire. Profil : {url_dashboard}'),
('M_freelance_debutant_creatif_2', 'M_freelance_debutant_creatif', 2, 72, 'Akossiwa, photographe debutante a Akpakpa, a poste un mini-portfolio (12 photos : 3 portraits, 3 evenements, 3 produits, 3 mariages), tarifs nets (shooting 25 000, evenement 50 000, produit 15 000). En 3 semaines, 4 contrats payes plein tarif. Toi {prenom} : portfolio nette + tarifs fixes = clients qui paient. Mets a jour : {url_dashboard}'),
('M_freelance_debutant_creatif_3', 'M_freelance_debutant_creatif', 3, 336, '{prenom}, parrainage 40% recurrent. Tu connais combien de creatifs ? Photographes, videastes, graphistes, monteurs, infographistes, designers ? Chaque pro que tu inscris en Plan Pro = 1 000 FCFA/mois recurrent. 15 parrains = 15 000 FCFA/mois passif. Pendant tu shoot, ton lien bosse. {url_parrainage}'),
('M_freelance_debutant_creatif_4', 'M_freelance_debutant_creatif', 4, 720, '{prenom}, 30 jours. Le Plan Pro 2 500 FCFA/mois = ton independance creative. Premier dans les recherches "photographe/videaste {ville}", badge Pro verifie (tu paraitres serieuse face aux concurrents free), King & Queen apres 2 mois. 2 500 FCFA = un demi-shooting. Tu vaux plus. Active : {url_dashboard}'),

-- M_freelance_confirme_creatif (creatif confirme)
('M_freelance_confirme_creatif_1', 'M_freelance_confirme_creatif', 1, 0, '{prenom}, photographe/videaste/graphiste confirme a {ville}. Tu as 3 ans d''exp, des clients fideles, mais tu plafonne. Pour passer a 500K/mois, il faut etre VU. Sur WOLO Market, ton portfolio est indexe, ta page pro affiche ton tarif day-rate, tes specialites (mariage, corporate, e-commerce). Les boites du quartier d''affaires te trouvent direct. Active : {url_dashboard}'),
('M_freelance_confirme_creatif_2', 'M_freelance_confirme_creatif', 2, 72, 'Sika, videaste confirmee a {ville}, a structure son profil ainsi : day-rate 75 000, demi-journee 40 000, montage 25 000/min, 20 photos signature dans portfolio, 3 testimonials clients. En 1 mois : 5 contrats corpo. Toi {prenom} : day-rate clair = clients pros qui ne discutent pas. Structure ton profil : {url_dashboard}'),
('M_freelance_confirme_creatif_3', 'M_freelance_confirme_creatif', 3, 336, '{prenom}, parrainage 40% recurrent. Tu travailles avec des creatifs : assistant photo, monteur, retoucheur, sound designer, makeup artist plateau. Chaque pro inscrit Pro grace a toi = 1 000 FCFA/mois recurrent. 15 parrains = 15 000 FCFA/mois passif. {url_parrainage}'),
('M_freelance_confirme_creatif_4', 'M_freelance_confirme_creatif', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = independance creative scaled. Premier dans recherches, badge Pro, King & Queen apres 2 mois (500K distribues/mois), publication d''offres si tu cherches assistant. 2 500 FCFA = un cafe Starbucks Lome. Active : {url_dashboard}'),

-- M_patron_studio (patron studio creatif/agence)
('M_patron_studio_1', 'M_patron_studio', 1, 0, '{prenom}, tu diriges un studio photo/video/graphique a {ville}. 3-8 creatifs, materiel, projets clients corpo. Probleme : tu cherches un monteur senior, un graphiste avance, un assistant studio. Les CV recus sont des copies/colles, portfolios bidons. Sur WOLO Market, profils verifies, portfolios reels, badges. Active recruteur : {url_dashboard}'),
('M_patron_studio_2', 'M_patron_studio', 2, 72, 'Wilfried, patron studio a {ville}, a recrute 1 monteur en 7 jours via WOLO. Offre : monteur Premiere/DaVinci, 120 000 FCFA/mois. Question knockout (envoie 1 reel monte de moins de 60s). 11 candidats, 4 retenus, 1 embauche. Toi {prenom} : exige preuve creative, gain de temps massif. {url_dashboard}'),
('M_patron_studio_3', 'M_patron_studio', 3, 336, '{prenom}, parrainage 40% recurrent. Tu connais des patrons agences com, studios prod, imprimeries ? 1 000 FCFA/mois par patron Pro inscrit. 10 parrains = 10 000 FCFA/mois recurrent. {url_parrainage}'),
('M_patron_studio_4', 'M_patron_studio', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = outil studio. Offres illimitees, pipeline candidats kanban, filtres (logiciels Premiere/After/Photoshop/Illustrator, exp), King & Queen entreprise apres 2 mois. 2 500 FCFA = une heure de drone location. Active : {url_dashboard}'),

-- ========== TRANSPORT ==========
-- M_salarie_plateforme_transport (Komlan, taxi salarie Yango/Bolt)
('M_salarie_plateforme_transport_1', 'M_salarie_plateforme_transport', 1, 0, '{prenom}, chauffeur Yango/Bolt/coursier livreur a {ville}. Tu connais le calcul : tu fais 25 000 FCFA dans la journee, la commission Yango prend 8 000, l''essence prend 7 000, il te reste 10 000 FCFA pour 12h de boulot. La commission de plateforme te dévore. Sur WOLO Market, des clients particuliers et entreprises te trouvent en direct (course privee, livraison hors-app). Tu encaisses 100%. Active : {url_dashboard}'),
('M_salarie_plateforme_transport_2', 'M_salarie_plateforme_transport', 2, 72, 'Komlan, chauffeur a Avedji, a fait ca : profil WOLO avec photo voiture, plaques, zone de service (aeroport-centre, banlieue-marche), tarifs hors-app (course aeroport 5 000, journee complete 25 000). 6 contrats prives en 2 semaines. 0 commission plateforme. Toi {prenom} : zones + tarifs = clients direct. Mets a jour : {url_dashboard}'),
('M_salarie_plateforme_transport_3', 'M_salarie_plateforme_transport', 3, 336, '{prenom}, parrainage 40% recurrent. Tu roules toute la journee, tu croises 50 chauffeurs, livreurs, coursiers, motos-taxis. Chaque pro inscrit Pro grace a ton lien = 1 000 FCFA/mois recurrent. 25 parrains = 25 000 FCFA/mois passif. C''est 1 jour de course en commission. {url_parrainage}'),
('M_salarie_plateforme_transport_4', 'M_salarie_plateforme_transport', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = ton independance vis-a-vis des plateformes etrangeres qui te prennent 30%. Premier dans recherches "chauffeur/livreur {ville}", badge Pro verifie, King WOLO apres 2 mois. 2 500 FCFA = 8L d''essence. Une course aeroport sans commission rembourse 2 mois. Active : {url_dashboard}'),

-- M_proprietaire_transport (chauffeur proprietaire)
('M_proprietaire_transport_1', 'M_proprietaire_transport', 1, 0, '{prenom}, chauffeur proprietaire de ton vehicule a {ville}. Tu n''as pas de patron, mais ton telephone est ton pire ennemi : il sonne ou il ne sonne pas. Sur WOLO Market, ton profil pro affiche photo voiture, vehicule (climatise oui/non), zones, tarifs. Les entreprises et particuliers fideles te trouvent direct. Active : {url_dashboard}'),
('M_proprietaire_transport_2', 'M_proprietaire_transport', 2, 72, 'Kofi, chauffeur proprio a {ville}, a structure son profil : voiture climatisee Toyota Corolla, photo, 4 services (course ville 2 500, aeroport 5 000, journee 25 000, deplacement Lome-Cotonou 35 000). 9 contrats en 3 semaines. Toi {prenom} : structure tes services. {url_dashboard}'),
('M_proprietaire_transport_3', 'M_proprietaire_transport', 3, 336, '{prenom}, parrainage 40% recurrent. Combien de chauffeurs, motos-taxis, coursiers tu connais ? 1 000 FCFA/mois par pro inscrit Pro grace a toi. 20 parrains = 20 000 FCFA/mois recurrent. {url_parrainage}'),
('M_proprietaire_transport_4', 'M_proprietaire_transport', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = independance des plateformes etrangeres. Premier dans recherches, badge Pro, King WOLO apres 2 mois (500K distribues), publication d''offres si tu prends un chauffeur partenaire. 2 500 FCFA = 8L d''essence. Active : {url_dashboard}'),

-- M_patron_flotte (patron flotte transport)
('M_patron_flotte_1', 'M_patron_flotte', 1, 0, '{prenom}, tu diriges une flotte (taxi, livraison, transport entreprise) a {ville}. 5-15 vehicules, autant de chauffeurs. Probleme : turn-over et chauffeurs peu fiables. Sur WOLO Market, profils verifies avec permis, anciens employeurs, scoring fiabilite. Active recruteur : {url_dashboard}'),
('M_patron_flotte_2', 'M_patron_flotte', 2, 72, 'Senou, patron flotte a {ville}, a recrute 3 chauffeurs en 8 jours via WOLO. Offre : chauffeur permis B, 60 000 FCFA/mois + commission. Question knockout (combien d''annees de conduite a {ville} ?). 18 candidats, 7 retenus, 3 embauches. Toi {prenom} : volume de candidats serieux + filtres = recrutement rapide. {url_dashboard}'),
('M_patron_flotte_3', 'M_patron_flotte', 3, 336, '{prenom}, parrainage 40% recurrent. Tu connais d''autres patrons flotte, agences voyage, transporteurs ? 1 000 FCFA/mois par patron Pro inscrit. 8 parrains = 8 000 FCFA/mois. {url_parrainage}'),
('M_patron_flotte_4', 'M_patron_flotte', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = outil flotte. Offres illimitees, pipeline candidats, filtres (annees permis, zone, type vehicule), King WOLO entreprise apres 2 mois. 2 500 FCFA = 8L essence pour 1 vehicule. Active : {url_dashboard}'),

-- ========== RESTAURATION ==========
-- M_apprenti_resto (Mariam, apprentie cuisine, Akpakpa Cotonou)
('M_apprenti_resto_1', 'M_apprenti_resto', 1, 0, '{prenom}, apprenti(e) cuisine/patisserie/serveur a {ville}. Le scenario : tu prepares 50 plats, le patron encaisse 100 000, toi tu pars avec 1 500 FCFA et 2 brochettes. Tes mains valent plus. Sur WOLO Market, tu te montres comme pro. Photos de tes plats, specialites (riz au gras, sauces, patisseries, service evenement). Les voisins du quartier qui font une fete viennent te chercher. Profil : {url_dashboard}'),
('M_apprenti_resto_2', 'M_apprenti_resto', 2, 72, 'Mariam, apprentie cuisine a Akpakpa, a poste 8 photos : 3 plats locaux, 2 patisseries, 3 buffets evenement. En 2 semaines, 3 voisins l''ont engagee pour des bapptemes/fetes (5 000 FCFA/jour service + plats). 15 000 FCFA en plus. Toi {prenom} : photos de TES plats, dispo evenement. {url_dashboard}'),
('M_apprenti_resto_3', 'M_apprenti_resto', 3, 336, '{prenom}, parrainage 40% recurrent. Tu connais combien de cuisiniers, patissiers, traiteurs, serveurs, livreurs resto ? Chaque pro inscrit Pro grace a toi = 1 000 FCFA/mois recurrent. 15 parrains = 15 000 FCFA/mois. {url_parrainage}'),
('M_apprenti_resto_4', 'M_apprenti_resto', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = ton independance cuisine. Premier dans recherches "traiteur/cuisinier {ville}", badge Pro, King & Queen apres 2 mois. 2 500 FCFA = 5 plats que tu factures direct. Active : {url_dashboard}'),

-- M_indep_resto (indep restauration)
('M_indep_resto_1', 'M_indep_resto', 1, 0, '{prenom}, traiteur/patissier/cuisinier independant a {ville}. Ton CA depend des bapptemes, mariages, fetes du quartier. Quand le quartier est calme, ton frigo se vide. Sur WOLO Market, profil pro indexe, photos de prestations, prix par formule (buffet 50 personnes 75 000, patisserie commande, cuisine domicile). Active : {url_dashboard}'),
('M_indep_resto_2', 'M_indep_resto', 2, 72, 'Aboubakar, traiteur indep a {ville}, a poste 12 photos buffets, 4 formules avec prix nets (buffet 30/50/80/120 pers), 6 specialites. 8 evenements en 1 mois. Toi {prenom} : formules claires = clients qui briefent vite. {url_dashboard}'),
('M_indep_resto_3', 'M_indep_resto', 3, 336, '{prenom}, parrainage 40% recurrent. Combien de traiteurs, patissiers, cuisiniers, gerants resto tu connais ? 1 000 FCFA/mois par pro inscrit Pro. 18 parrains = 18 000 FCFA/mois. {url_parrainage}'),
('M_indep_resto_4', 'M_indep_resto', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = independance. Premier dans recherches, badge Pro, King & Queen apres 2 mois, publication offres aide cuisine. 2 500 FCFA = 1 buffet 4 personnes. Active : {url_dashboard}'),

-- M_patron_resto (patron resto/maquis)
('M_patron_resto_1', 'M_patron_resto', 1, 0, '{prenom}, tu diriges un resto/maquis/patisserie a {ville}. 5-15 employes (cuisine, salle, bar, livreurs). Probleme constant : turn-over en salle, cuisinier absent, recrutement lent. Sur WOLO Market, profils verifies, photos plats des candidats cuisine, scoring fiabilite serveurs. Active recruteur : {url_dashboard}'),
('M_patron_resto_2', 'M_patron_resto', 2, 72, 'Bertille, patronne resto a {ville}, a recrute 1 chef rang + 1 cuisinier en 6 jours via WOLO. Offres claires (chef rang 50 000/mois + pourboires, cuisinier 75 000/mois), questions knockout. 24 candidats, 6 retenus, 2 embauches. Toi {prenom} : offres precises = candidats serieux. {url_dashboard}'),
('M_patron_resto_3', 'M_patron_resto', 3, 336, '{prenom}, parrainage 40% recurrent. Tu connais d''autres patrons resto, bars, hotels ? 1 000 FCFA/mois par patron Pro inscrit. 12 parrains = 12 000 FCFA/mois. {url_parrainage}'),
('M_patron_resto_4', 'M_patron_resto', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = outil resto. Offres illimitees, pipeline kanban, filtres (cuisine locale/internationale, salle, bar), King & Queen entreprise apres 2 mois. 2 500 FCFA = 5 plats. Ton resto vaut plus. Active : {url_dashboard}'),

-- ========== DIGITAL ==========
-- M_freelance_debutant_digital (Kossi, freelance dev debutant Lome)
('M_freelance_debutant_digital_1', 'M_freelance_debutant_digital', 1, 0, '{prenom}, freelance digital debutant a {ville} (dev, CM, redacteur, designer UI). Le truc tu le vis deja : un client te commande un site, livre, et "je te paie la semaine prochaine". 3 mois apres, toujours rien. Sur WOLO Market, profil pro avec tarifs nets, conditions paiement (50% acompte), portfolio. Le client serieux paie. Active : {url_dashboard}'),
('M_freelance_debutant_digital_2', 'M_freelance_debutant_digital', 2, 72, 'Kossi, freelance dev debutant a Lome, a structure son profil : 4 specialites (site vitrine 75 000, e-commerce Shopify 150 000, application web simple 250 000, maintenance 25 000/mois), conditions (50% acompte). 5 contrats en 1 mois, 0 impaye. Toi {prenom} : tarifs + acompte = clients serieux uniquement. {url_dashboard}'),
('M_freelance_debutant_digital_3', 'M_freelance_debutant_digital', 3, 336, '{prenom}, parrainage 40% recurrent. Tu connais combien de freelances digitaux ? Devs, CM, redacteurs, designers UI/UX, video editors, illustrateurs ? Chaque inscription Pro grace a ton lien = 1 000 FCFA/mois recurrent. 20 parrains = 20 000 FCFA/mois passif. {url_parrainage}'),
('M_freelance_debutant_digital_4', 'M_freelance_debutant_digital', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = ton independance. Premier dans recherches "dev/CM/designer {ville}", badge Pro verifie (clients serieux te font confiance), King & Queen apres 2 mois. 2 500 FCFA = 1h de tarif freelance. Active : {url_dashboard}'),

-- M_freelance_confirme_digital (confirme)
('M_freelance_confirme_digital_1', 'M_freelance_confirme_digital', 1, 0, '{prenom}, freelance digital confirme a {ville}. 2-5 ans d''exp, clients fideles, mais ton scaling bute sur la prospection. Sur WOLO Market, tu apparais en haut des recherches, ton portfolio est visible, ton day-rate est annonce. Les boites locales (banques, telco, NGOs) te trouvent. Active : {url_dashboard}'),
('M_freelance_confirme_digital_2', 'M_freelance_confirme_digital', 2, 72, 'Edem, dev senior a {ville}, a affiche : day-rate 100 000 FCFA, packages mensuels (retainer maintenance 200 000/mois, audit 150 000, refonte 800 000), 4 testimonials. 3 contrats corpo en 1 mois. Toi {prenom} : structure premium = clients premium. {url_dashboard}'),
('M_freelance_confirme_digital_3', 'M_freelance_confirme_digital', 3, 336, '{prenom}, parrainage 40% recurrent. Tu collabores avec des designers, copywriters, videoeditors, devs back, devs front. Chaque inscription Pro grace a toi = 1 000 FCFA/mois recurrent. 20 parrains = 20 000 FCFA/mois passif. {url_parrainage}'),
('M_freelance_confirme_digital_4', 'M_freelance_confirme_digital', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = independance creative scaled. Premier dans recherches, badge Pro, King & Queen apres 2 mois (500K distribues), publication d''offres pour sous-traitance. 2 500 FCFA = 15 minutes de ton day-rate. Active : {url_dashboard}'),

-- M_employe_digital (employe agence digitale)
('M_employe_digital_1', 'M_employe_digital', 1, 0, '{prenom}, tu es employe(e) en agence digitale a {ville} (dev, CM, designer, redacteur). Tu fais le travail, l''agence facture 5x ton salaire, tu touches 80 000-150 000 FCFA. Tu sais tu peux gagner plus en direct. Sur WOLO Market, profil freelance perso, portfolio (sans clients agence pour eviter les conflits), specialites perso. Tu commences a prendre des side-projects le week-end. Active : {url_dashboard}'),
('M_employe_digital_2', 'M_employe_digital', 2, 72, 'Yvette, employee agence a {ville}, a cree son profil WOLO le soir : portfolio personnel (3 projets perso non-agence), tarifs week-end (logo 25 000, flyer 10 000, page produit 35 000). 4 side-clients en 1 mois = 100 000 FCFA en plus de son salaire. Toi {prenom} : side-projects = independance progressive. {url_dashboard}'),
('M_employe_digital_3', 'M_employe_digital', 3, 336, '{prenom}, parrainage 40% recurrent. Tu connais des collegues agence, freelances, indeps digitaux ? 1 000 FCFA/mois par pro inscrit Pro grace a toi. 15 parrains = 15 000 FCFA/mois passif. C''est 0 effort apres setup. {url_parrainage}'),
('M_employe_digital_4', 'M_employe_digital', 4, 720, '{prenom}, 30 jours. Plan Pro 2 500 FCFA/mois = ton plan B et bientot ton plan A. Premier dans recherches, badge Pro, King & Queen apres 2 mois, side-revenue qui grandit. 2 500 FCFA = 30 min de ton tarif freelance. Active : {url_dashboard}')

ON CONFLICT (key) DO NOTHING;
